apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - cluster: kind-scribble
  template:
    metadata:
      name: '{{.cluster}}-myapp'
    spec:
      project: myproj
      source:
        repoURL: https://github.com/bsalsingh/argo-app-set.git
        targetRevision: HEAD
        path: blaze/{{.cluster}}
      destination:
        name: '{{.cluster}}'
        namespace: myapp
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true


