apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - cluster: in-cluster
            path: dev
  template:
    metadata:
      name: '{{.cluster}}-{{.path}}-myapp'
    spec:
      project: default
      source:
        repoURL: https://github.com/bsalsingh/argo-app-set.git
        targetRevision: HEAD
        path: '{{.path}}'
      destination:
        name: '{{.cluster}}'
        namespace: '{{.path}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
